=== rubensa/springframework/spring/src/org/springframework/beans/factory/xml/spring-beans.dtd
<!--
	Spring XML BeanFactory DTD.
	Author: Rod Johnson
	
	This defines a simple and consistent way of creating a namespace
	of JavaBeans configured by a Spring XmlBeanFactory.
	
	This document type is used by most Spring functionality, including
	web application contexts, which are based on BeanFactories.
	
	Each <bean> element in this document defines a JavaBean.
	Typically the bean class is specified, along with JavaBean
	properties.
	
	References among beans are supported (setting a JavaBean
	property to refer to another bean in the same factory).
	
	Bean instances can be "singletons" (shared instances)
	or "prototypes" (independent instances).
	
	There is also support for lists, maps, and 
	java.util.Properties types.
	
	As the format is simple, a DTD is sufficient, and there's
	no need for a schema at this point.
	
	$Id$
-->

<!-- 
	The document root.
	At least one bean definition is required.
-->

<!ELEMENT beans (
        bean+
)>

<!--
  Default values for all bean definitions. Can be overridden at
  the "bean" level. See those attribute definitions for details.
-->
<!ATTLIST beans default-dependency-check (none | objects | simple | all) "none">
<!ATTLIST beans default-autowire (no | byName | byType) "no">

<!--
	Defines a single named bean.
-->
<!ELEMENT bean (
        (constructor-arg | property)*
)>

<!--
	All beans are identified by an id, to enable reference checking.
	There are constraints on a valid XML id: if you want to reference
	your bean in Java code using a name that's illegal as an XML id,
	use the optional "name" attribute.
-->
<!ATTLIST bean id ID #IMPLIED>

<!--
	Optional. Can be used to create an alias illegal in an id.
-->
<!ATTLIST bean name CDATA #IMPLIED>

<!--
	Each bean definition must specify the FQN of the class,
	or the name of the parent bean from which the class can be worked out.

	Note that a child bean definition that references a parent will just
	add respectively override property values and be able to change the
	singleton status. It will inherit all of the parent's other parameters
	like lazy initialization or autowire settings.
-->
<!ATTLIST bean class CDATA #IMPLIED>
<!ATTLIST bean parent CDATA #IMPLIED>

<!--
	Is this bean a "singleton" (one shared instance, which will
	be returned by all calls to getBean() with the id),
	or a "prototype" (independent instance resulting from each call to
	getBean(). Default is singleton.

	Singletons are most commonly used, and are ideal for multi-threaded
	service objects.
-->
<!ATTLIST bean singleton (true | false) "true">

<!--
  If this bean should be lazily initialized.
	If false, it will get instantiated on startup by bean factories
	that perform eager initialization of singletons.
-->
<!ATTLIST bean lazy-init (true | false) "false">

<!--
	Optional attribute controlling whether to check whether all this
	beans dependencies, expressed in its properties, are satisfied.
	Default is no dependency checking.
	"simple" type dependency checking includes primitives and String
	"object" includes collaborators (other beans in the factory)
	"all" includes both types of dependency checking
-->
<!ATTLIST bean dependency-check (none | objects | simple | all | default) "default">

<!--
	Optional attribute controlling whether to "autowire"
	bean properties. This is an automagical process in which bean references
	don't need to be coded explicitly in the XML bean definition file,
	but Spring works out dependencies.

	There are three modes:

	1. no
	The traditional Spring default. No automagical wiring. Bean references
	must be defined in the XML file via the <ref> element. We recommend this
	in most cases as it makes documentation more explicit.

	2. byName
	Autowiring by property name. If a bean of class Cat exposes a dog property,
	Spring will try to set this to the value of the bean "dog" in the current
	factory.

	3. byType
	This is like the PicoContainer default, in which there must be exactly
	one bean of the property type in the bean factory. If there are 0 or
	more than one, a fatal error is raised, and you can't use byType autowiring
	for that bean.
	This makes bean factories simple to configure for small namespaces,
	but doesn't work as well as standard Spring behaviour for
	bigger applications.

	Autowire behaviour can be combined with dependency checking, which will
	be performed after all auto wiring has been completed.
-->
<!ATTLIST bean autowire (no | byName | byType | constructor | default) "default">

<!-- 
	Optional attribute for the name of the custom initialization method
	to invoke after setting bean properties. The method must have no arguments,
	but may throw any exception. 
-->
<!ATTLIST bean init-method CDATA #IMPLIED>

<!--
	Optional attribute for the name of the custom destroy method to invoke
	on bean factory shutdown. The method must have no arguments,
	but may throw any exception. Note: Only invoked on singleton beans!
-->
<!ATTLIST bean destroy-method CDATA #IMPLIED>

<!--
	Bean definitions can specify zero or more constructor arguments.
	They correspond to either a specific index of the constructor argument list
	or are supposed to be matched generically by type.
	This is an alternative to "autowire constructor".
-->
<!ELEMENT constructor-arg (
        (value | ref | list | map | props)
)>

<!--
	Bean definitions can have zero or more properties. 
	Property elements correspond to JavaBean setter methods exposed
	by the bean classes. Spring supports primitives, references to other
	beans in the same or related factories, lists, maps and properties.
-->
<!ELEMENT property (
        (value | ref | list | map | props)
)>

<!ATTLIST constructor-arg index CDATA #IMPLIED>

<!--
	The property name attribute is the name of the JavaBean property.
	This follows JavaBean conventions: a name of "age" would correspond
	to setAge()/optional getAge() methods.
-->
<!ATTLIST property name CDATA #REQUIRED>

<!--
	Defines a reference to another bean in this factory or an external
	factory (parent or included factory). 
-->
<!ELEMENT ref EMPTY>

<!--
	Contains a string representation of a property value.
	The property may be a string, or may be converted to the
	required type using the JavaBeans PropertyEditor
	machinery. This makes it possible for application developers
	to write custom PropertyEditor implementations that can
	convert strings to objects. 
	
	Note that this is recommended for simple objects only.
	Configure more complex objects by setting JavaBean
	properties to references to other beans.
-->
<!ELEMENT value (#PCDATA)>

<!--
	References must specify a name of the target bean.
	The "bean" attribute can reference any name from any bean in the context,
	to be checked at runtime.
	Local references, using the "local" attribute, have to use bean ids;
	they can be checked by this DTD, thus should be preferred for references
	within the same bean factory XML file.
	The "external" attribute can be used to explictly indicate a reference to
	a bean outside the current XML file; they can be checked only at runtime,
	just like the generic "bean" attribute.
-->
<!ATTLIST ref bean CDATA #IMPLIED>
<!ATTLIST ref local IDREF #IMPLIED>
<!ATTLIST ref external CDATA #IMPLIED>

<!--
	A list can contain multiple value and/or ref elements.
	Java lists are untyped, pending generics support in Java 1.5. 
	although references will be strongly typed. 
	A list can also map to an array type. The necessary conversion
	is automatically performed by the Spring AbstractBeanFactory. 
-->
<!ELEMENT list (
        (value | ref)*
)>

<!--
	A Spring map is a mapping from a string key to object.
	Maps may be empty.
-->
<!ELEMENT map (
        (entry)*
)>

<!--
	A map entry can be a value, ref or list
	The name of the property is given by the "key" attribute.
-->
<!ELEMENT entry (
        (value | ref | list | map)*
)>

<!ATTLIST entry key CDATA #REQUIRED>

<!--
	Props elements differ from map elements in that values must be strings.
	Props may be empty.
-->
<!ELEMENT props (
        (prop)*
)>

<!--
	Element content is the string value of the property. The "key"
	attribute is the name of the property.
-->
<!ELEMENT prop
        (#PCDATA)
>

<!--
	Each property element must specify the key. The value
	is the element content.
-->
<!ATTLIST prop key CDATA #REQUIRED>

=== rubensa/springframework/spring/test/org/springframework/scripting/groovy/groovyRefreshableContext.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE beans PUBLIC "-//SPRING//DTD BEAN//EN" "http://www.springframework.org/dtd/spring-beans.dtd">

<beans>

	<bean class="org.springframework.scripting.support.ScriptFactoryPostProcessor">
		<property name="refreshCheckDelay" value="1"/>
	</bean>

	<bean id="calculator" class="org.springframework.scripting.groovy.GroovyScriptFactory">
		<constructor-arg value="classpath:org/springframework/scripting/groovy/Calculator.groovy"/>
	</bean>

	<bean id="messenger" class="org.springframework.scripting.groovy.GroovyScriptFactory">
		<constructor-arg value="classpath:org/springframework/scripting/groovy/Messenger.groovy"/>
		<property name="message" value="Hello World!"/>
	</bean>

</beans>

=== rubensa/springframework/spring/test/org/springframework/aop/framework/autoproxy/advisorAutoProxyCreator.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE beans PUBLIC  "-//SPRING//DTD BEAN//EN" "http://www.springframework.org/dtd/spring-beans.dtd">

<!--
	Common bean definitions for EnterpriseServices
	tests.
-->
<beans>

	<bean id="aapc"
		class="org.springframework.aop.framework.autoproxy.AdvisorAutoProxyCreator">
	</bean>


	<bean id="aapc.txManager"
		class="org.springframework.transaction.CountingTxManager">
	</bean>
	
	<bean id="tas" class="org.springframework.transaction.interceptor.PropertiesTransactionAttributeSource">
		<property name="properties">
			<props>
				<prop key="set*">PROPAGATION_REQUIRED</prop>
				<prop key="rollbackOnly">PROPAGATION_REQUIRED</prop>
				<prop key="echoException">PROPAGATION_REQUIRED,+javax.servlet.ServletException,-java.lang.Exception</prop>
			</props>
		</property>
	</bean>
	
	
	<bean id="aapc.txInterceptor" class="org.springframework.transaction.interceptor.TransactionInterceptor">
		<property name="transactionManager"><ref local="aapc.txManager"/></property>
		<property name="transactionAttributeSource"><ref local="tas"/></property>
	</bean>
	
	
	<bean id="aapc.txAdvice"
		autowire="constructor"
		class="org.springframework.transaction.interceptor.TransactionAttributeSourceTransactionAroundAdvisor">
	</bean>
	
	
	<bean id="test"
		class="org.springframework.beans.TestBean">
		<property name="age"><value>4</value></property>
	</bean>
	
	<bean id="noSetters"
		class="org.springframework.aop.framework.autoproxy.NoSetters">

	</bean>
	
	<bean id="rollback"
		class="org.springframework.aop.framework.autoproxy.Rollback">

	</bean>
	

</beans>

=== rubensa/springframework/spring/sandbox/test/org/springframework/beans/factory/dynamic/persist/simple.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE beans PUBLIC "-//SPRING//DTD BEAN//EN" "http://www.springframework.org/dtd/spring-beans.dtd">

<!--
  - Application context definition for Petclinic on JDBC.
	-->
<beans>
	
	<bean id="groovyScriptFactory"
		class="org.springframework.beans.factory.groovy.GroovyScriptFactory"
	>
		<property name="expirySeconds"><value>20</value></property>
	</bean>
	 
	<bean id="simpleSingleton"
		factory-bean="groovyScriptFactory"
		factory-method="create"
	>
		<constructor-arg index="0"><value>org/springframework/beans/factory/groovy/SimpleHello.groovy</value></constructor-arg>
	</bean>
	
	<!--
		Must be a singleton or the DynamicScriptInterceptor
		fails when getting the bean from the factory
	-->
	<bean id="propertySingleton"
		singleton="true"
		factory-bean="groovyScriptFactory"
		factory-method="create"
	>
		<constructor-arg index="0"><value>org/springframework/beans/factory/groovy/PropertyHello.groovy</value></constructor-arg>
		
		<!-- Property on created Groovy object -->
		<property name="message"><value>hello world property</value></property>
	</bean>
	
	<bean id="propertyPrototype"
		singleton="false"
		factory-bean="groovyScriptFactory"
		factory-method="create"
	>
		<constructor-arg index="0"><value>org/springframework/beans/factory/groovy/PropertyHello.groovy</value></constructor-arg>
		
		<!-- Property on created Groovy object -->
		<property name="message"><value>propertyPrototype</value></property>
	</bean>
	
	<bean id="dependsOnProperty" 
		class="org.springframework.beans.factory.groovy.DelegatingHello">
		<!-- Depends on dynamic hello -->
		<property name="hello"><ref local="propertySingleton"></ref></property>
	</bean>
	
	<bean id="bad"
		factory-bean="groovyScriptFactory"
		factory-method="create"
		singleton="false"
	>
		<constructor-arg index="0"><value>org/springframework/beans/factory/groovy/Bad.groovy</value></constructor-arg>
	</bean>

	
</beans>

=== rubensa/springframework/spring/test/org/springframework/aop/framework/support/advisorAutoProxyCreator.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE beans PUBLIC  "-//SPRING//DTD BEAN//EN" "http://www.springframework.org/dtd/spring-beans.dtd">

<!--
	Common bean definitions for EnterpriseServices
	tests.
-->
<beans>

	<bean id="auto_txPP"
		class="org.springframework.aop.framework.support.AdvisorAutoProxyCreator">
	</bean>


	<bean id="auto_txManager"
		class="org.springframework.transaction.CountingTxManager">
	</bean>
	
	<bean id="tas" class="org.springframework.transaction.interceptor.PropertiesTransactionAttributeSource">
		<property name="properties">
			<props>
				<prop key="set*">PROPAGATION_REQUIRED</prop>
				<prop key="rollbackOnly">PROPAGATION_REQUIRED</prop>
				<prop key="echoException">PROPAGATION_REQUIRED,+javax.servlet.ServletException,-java.lang.Exception</prop>
			</props>
		</property>
	</bean>
	
	
	<bean id="auto_txInterceptor" class="org.springframework.transaction.interceptor.TransactionInterceptor">
		<property name="transactionManager"><ref local="auto_txManager"/></property>
		<property name="transactionAttributeSource"><ref local="tas"/></property>
	</bean>
	
	
	<bean id="auto_txAdvice"
		autowire="constructor"
		class="org.springframework.transaction.interceptor.TransactionAttributeSourceTransactionAroundAdvisor">
	</bean>
	
	
	<bean id="test"
		class="org.springframework.beans.TestBean">
		<property name="age"><value>4</value></property>
	</bean>
	
	<bean id="noSetters"
		class="org.springframework.aop.framework.support.NoSetters">

	</bean>
	
	<bean id="rollback"
		class="org.springframework.aop.framework.support.Rollback">

	</bean>
	

</beans>

=== rubensa/springframework/spring/samples/webflow/phonebook/src/org/springframework/samples/phonebook/deploy/web-layer.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE beans PUBLIC "-//SPRING//DTD BEAN//EN" "http://www.springframework.org/dtd/spring-beans.dtd">

<beans>

	<!-- search flow beans -->
	
	<!-- Xml FlowBuilder definition for the search flow -->
	<bean id="person.Search" class="org.springframework.web.flow.config.XmlFlowFactoryBean">
		<property name="location" value="classpath:org/springframework/samples/phonebook/web/flow/search-flow.xml"/>
	</bean>
	
	<!-- Java FlowBuilder definition for the search flow.
	     Uncomment if you wish to plugin this FlowBuilder instead of the xml implementation!
	     (be sure to comment out the xml variant)
	     Notice the consistency: you may plug in any other FlowBuilder implementation in
	     exactly the same fashion -->
	<!--
	<bean id="person.Search" class="org.springframework.web.flow.config.FlowFactoryBean">
		<property name="flowBuilder">
			<bean class="org.springframework.samples.phonebook.web.flow.SearchPersonFlowBuilder" autowire="byType"/>
		</property>
	</bean>
	-->
	
	<bean id="person.Search.criteria.formAction" class="org.springframework.web.flow.action.FormAction">
		<property name="formObjectName" value="query"/>
		<property name="formObjectClass" value="org.springframework.samples.phonebook.domain.PhoneBookQuery"/>
		<property name="formObjectScopeAsString" value="flow"/>
		<property name="validator">
			<bean class="org.springframework.samples.phonebook.domain.PhoneBookQueryValidator"/>
		</property>
	</bean>

	<bean id="person.Search.executeQuery" class="org.springframework.samples.phonebook.web.flow.action.ExecuteQueryAction" autowire="byType"/>

	<!-- The event parameter mapper action sets request parameters as attributes in the flow model.
	     The exact mapping(s) policies are fully configurable; in this case, the
	     "id" request parameter is mapped to the "id" attribute and converted
	     to a java.lang.Long in the target flow model!  -->
	<bean id="person.Search.id.set" class="org.springframework.web.flow.action.EventParameterMapperAction">
		<property name="mapping" value="id,java.lang.Long"/>
		<property name="targetScopeAsString" value="flow"/>
	</bean>

	<!-- detail flow beans -->

	<!-- xml FlowBuilder definition for the detail flow -->
	<bean id="person.Detail" class="org.springframework.web.flow.config.XmlFlowFactoryBean">
		<property name="location" value="classpath:org/springframework/samples/phonebook/web/flow/detail-flow.xml"/>
	</bean>
	
	<!-- Java flow builder definition for the detail flow.
	     Uncomment if you wish to plugin this flow builder instead of the xml implementation!
	     (be sure to comment out the xml variant)
	     Notice the consistency: you may plug in any other FlowBuilder implementation in
	     exactly the same fashion -->
	<!--
	<bean id="person.Detail" class="org.springframework.web.flow.config.FlowFactoryBean">
		<property name="flowBuilder">
			<bean class="org.springframework.samples.phonebook.web.flow.PersonDetailFlowBuilder" autowire="byType"/>
		</property>
	</bean>
	-->
	
	<!-- The event parameter mapper action sets request parameters as attributes in flow scope.
	     The exact mapping(s) policies are fully configurable; in this case, the
	     "id" request parameter is mapped to the "colleagueId" attribute and converted
	     to a java.lang.Long in the target flow scope!  -->
	<bean id="person.Detail.colleagueId.set" class="org.springframework.web.flow.action.EventParameterMapperAction">
		<property name="mapping" value="id->colleagueId,java.lang.Long"/>
		<property name="targetScopeAsString" value="flow"/>
	</bean>
		
	<!-- A type conversion service, a more flexible/threadsafe/lightweight alternative to the PropertyEditor! -->
	<bean id="conversion.service" class="org.springframework.binding.convert.support.DefaultConversionService" autowire="byType"/>

	<!-- A formatter registry, a thread-safe cache for Formatters: a thread-safe, lighter weight alt. to PropertyEditors! -->
	<bean id="formatter.locator" class="org.springframework.binding.format.support.ThreadLocalFormatterLocator" autowire="byType"/>

	<!-- A broadcaster that will notify the formatter registry to cleanup all thread locals on app shutdown -->
	<bean id="thread.cleanupBroadcaster" class="org.springframework.binding.thread.support.DefaultThreadCleanupBroadcaster"/>

</beans>

=== rubensa/springframework/spring/samples/lightcountries/war/WEB-INF/lcountries-servlet.xml
<?xml version="1.0" encoding="UTF-8" ?>
<!DOCTYPE beans PUBLIC "-//SPRING//DTD BEAN//EN" "http://www.springframework.org/dtd/spring-beans.dtd">

<beans>

	<!-- ===========================================================-->
	<!-- Views														-->
	<!-- ===========================================================-->
	<!-- Explicit view mappings in bundle instead of default InternalResourceViewResolver.
	  - Fetches the view mappings from localized "views_xx" classpath files, i.e.
	  - "/WEB-INF/classes/views-countries.properties" or "/WEB-INF/classes/views-countries_fr.properties".
	  -
	  - Symbolic view names returned by controllers will be resolved in the respective
	  - properties file, allowing for arbitrary mappings between names and resources.
	  -
	  - We use the "defaultParentView" property. All views defined will inherit by default the properties
	  - defined in the "modelView" view.
	  -->
	<bean id="viewResolver" class="org.springframework.web.servlet.view.ResourceBundleViewResolver">			
		<property name="basename"><value>views-lcountries</value></property>
		<property name="defaultParentView"><value>modelView</value></property>
	</bean>

	<!-- ===========================================================-->
	<!-- Resolvers													-->
	<!-- ===========================================================-->
	<!-- We specify here that Locale and theme are stored in cookies.
	     They could be stored in a Session. Default resolvers don't allow changing them on the fly.
	-->
	<bean id="localeResolver" class="org.springframework.web.servlet.i18n.CookieLocaleResolver"/>
	<bean id="themeResolver" class="org.springframework.web.servlet.theme.CookieThemeResolver"/>

	<!-- ===========================================================-->
	<!-- Interceptors												-->
	<!-- ===========================================================-->
	<!-- Interceptors will pre-handle any request in this servlet, no matter which is the controller 
	     mapped for this request.
	     We use two built-in interceptors to detect user locale or theme change requests.
	     
	     The third interceptor is specific to this Demo. It allows views to easily be aware
	     about the configuration detected. Precisely to know if a copy data to database can be 
	     proposed to the user.
	-->
	<bean id="localeChangeInterceptor" class="org.springframework.web.servlet.i18n.LocaleChangeInterceptor"/>
	<bean id="themeChangeInterceptor" class="org.springframework.web.servlet.theme.ThemeChangeInterceptor"/>

	<!-- ===========================================================-->
	<!-- Mapping													-->
	<!-- ===========================================================-->
	<!--
	 - Explicit URL handler mapping instead of default BeanNameUrlHandlerMapping.
	 -->
	<bean id="urlMapping" class="org.springframework.web.servlet.handler.SimpleUrlHandlerMapping"> 
		<property name="interceptors">
			<list>
				<ref bean="localeChangeInterceptor"/>
				<ref bean="themeChangeInterceptor"/>
			</list>
		</property>
		<property name="mappings">
			<props>
				<prop key="/home.htm">lcountriesController</prop>
				<prop key="/config.htm">lcountriesController</prop>
				<prop key="/main/home.htm">lcountriesController</prop>
				<prop key="/main/detail.htm">lcountriesController</prop>
				<prop key="/main/countries.xls">lcountriesController</prop>
				<prop key="/main/countries.pdf">lcountriesController</prop>
				<prop key="/notfound.htm">errorsController</prop>
			</props>
		</property>
	</bean>
  
	<!-- ===========================================================-->
	<!-- Controllers												-->
	<!-- ===========================================================-->
	<!-- MultiControllers need a MethodNameResolver to mapping URLs to methods. -->

	<!-- ===========================================================-->
	<!-- General use Multiaction controller for Errors -->

	<bean id="errorsMethodNameResolver" class="org.springframework.web.servlet.mvc.multiaction.PropertiesMethodNameResolver">
		<property name="mappings">
			<props>
				<prop key="/notfound.htm">handleHttp404</prop>
			</props>
		</property>
	</bean>

	<bean id="errorsController" class="org.springframework.samples.lightcountries.web.ErrorsController">
		<property name="methodNameResolver"><ref bean="errorsMethodNameResolver"/></property>
	</bean>

	<!-- ===========================================================-->
	<!-- Application specific Multiaction controller -->

	<bean id="lcountriesMethodNameResolver" class="org.springframework.web.servlet.mvc.multiaction.PropertiesMethodNameResolver">
		<property name="mappings">
			<props>
				<prop key="/home.htm">handleHome</prop>
				<prop key="/config.htm">handleConfig</prop>
				<prop key="/main/home.htm">handleMain</prop>
				<prop key="/main/detail.htm">handleDetail</prop>
				<prop key="/main/countries.xls">handleExcel</prop>
				<prop key="/main/countries.pdf">handlePdf</prop>
			</props>
		</property>
	</bean>

	<bean id="lcountriesController" class="org.springframework.samples.lightcountries.web.CountriesController">
		<property name="methodNameResolver"><ref bean="lcountriesMethodNameResolver"/></property>
		<property name="daoCountry"><ref external="daoCountry"/></property>
		<!--
		<property name="homeView"><value>homeView</value></property>
		<property name="configView"><value>configView</value></property>
		<property name="mainView"><value>countries_mainView</value></property>
		<property name="detailView"><value>countries_detailView</value></property>
		<property name="excelView"><value>countries_excelView</value></property>
		<property name="pdfView"><value>countries_pdfView</value></property>
		-->
	</bean>
	
</beans>

=== rubensa/springframework/spring/sandbox/test/org/springframework/beans/factory/support/factory-methods.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE beans PUBLIC "-//SPRING//DTD BEAN//EN" "http://www.springframework.org/dtd/spring-beans.dtd">

<beans>
    <bean id="matchManager" class="org.springframework.beans.factory.support.MatchManager">
        <replaced-method name="createMatch" replacer="methodReplacer"/>
    </bean>

    <bean id="methodReplacer" class="org.springframework.beans.factory.support.FactoryMethodReplacer">
        <lookup-method name="getBean" bean="match"/>
    </bean>

    <bean id="match" class="org.springframework.beans.factory.support.Match" singleton="true">
        <constructor-arg>
            <bean class="org.springframework.beans.factory.support.FactoryMethodArguments" factory-method="getFirstArgument"/>
        </constructor-arg>
        <constructor-arg>
            <bean class="org.springframework.beans.factory.support.FactoryMethodArguments" factory-method="getSecondArgument"/>
        </constructor-arg>
        <constructor-arg>
            <bean class="org.springframework.beans.factory.support.FactoryMethodArguments" factory-method="getThirdArgument"/>
        </constructor-arg>
    </bean>
</beans>

=== rubensa/springframework/spring-projects/spring-webflow/src/test/org/springframework/webflow/execution/applicationContext.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE beans PUBLIC "-//SPRING//DTD BEAN//EN" 
	"http://www.springframework.org/dtd/spring-beans.dtd">

<!-- Application context definition -->

<beans>

	<bean id="flowExecutionManager" class="org.springframework.webflow.execution.FlowExecutionManager">
		<constructor-arg>
			<bean class="org.springframework.webflow.execution.FlowExecutionManagerTests$SimpleFlowLocator"/>
		</constructor-arg>
		<property name="storage">
			<bean class="org.springframework.webflow.execution.ContinuationDataStoreFlowExecutionStorage"/>
		</property>
		<property name="listener">
			<bean class="org.springframework.webflow.execution.FlowExecutionManagerTests$SimpleFlowExecutionListener"/>
		</property>
		<property name="transactionSynchronizer">
			<bean class="org.springframework.webflow.execution.DataStoreTokenTransactionSynchronizer"/>
		</property>
	</bean>

</beans>
