=== rubensa/springframework/spring/sandbox/src/org/springframework/web/flow/config/spring-webflow.dtd
<?xml version="1.0" encoding="UTF-8"?>

<!--
	Spring Web Flow DTD
	Authors: Erwin Vervaet, Keith Donald
	
	This DTD defines the web flow XML syntax. Web flows capture the page flow
	in (part of) a web application.

	XML documents that conform to this DTD should declare the following doctype:

	<!DOCTYPE webflow PUBLIC "-//SPRING//DTD WEBFLOW//EN"
		"http://www.springframework.org/dtd/spring-webflow.dtd">
-->

<!--
	Defines the root element for a web flow definition. Web flows
	are composed of one or more states.
-->
<!ELEMENT webflow ( (action-state | view-state | subflow-state | end-state | precondition )+ )>

<!--
	Unique identifier of the web flow; should be unique to all other web flows.
-->
<!ATTLIST webflow id ID #REQUIRED>

<!--
	Identifies the start state of the flow: the state where flow
	execution will begin.
-->
<!ATTLIST webflow start-state IDREF #REQUIRED>

<!--
	Defines an action state: a state where an action is executed.
	Transitions triggered by the action(s) lead on to other states.
-->
<!ELEMENT action-state ( action+, transition+ )>

<!--
	Unique identifier of an action state; must be unique to this flow.
-->
<!ATTLIST action-state id ID #REQUIRED>

<!--
	Defines a single action to be executed.
-->
<!ELEMENT action ( property* )>

<!--
	Identifier of the action implementation exported in the configured registry, typically
	the Spring Bean Factory. This is similar to the <ref bean="myBean"/> notation of
	the Spring beans DTD.
-->
<!ATTLIST action bean CDATA #IMPLIED>

<!--
	Fully qualified class of the Action implementation. An instance of the
	class will be instantiated and possibly autowired depending on the value of the
	autowire attribute.
-->
<!ATTLIST action class CDATA #IMPLIED>
	
<!--
	Dependency (aka collaborator) autowiring options for use when instantiating the action 
	implementation with the class attribute.
-->
<!ATTLIST action autowire (no | byName | byType | constructor | autodetect | default) "default">

<!--
	Fully qualified implementation class of the Action exported in the configured registry.
	For this "by type" action lookup to work, there must be exactly one Action implementation
	exported of that type.
-->
<!ATTLIST action classref CDATA #IMPLIED>

<!--
	Optional name qualifier for the action. When specified, the action will
	qualify execution result event identifiers by this name. An action with
	a name is ofter referred to as a "named action".
-->
<!ATTLIST action name CDATA #IMPLIED>

<!--
	Name of the target method to be invoked to execute this action.  The method's signature must
	be of the form: 'public Event ${method}(RequestContext)'
-->
<!ATTLIST action method CDATA #IMPLIED>

<!--
	A property associated with an action in an action state. Properties are simple strings that 
	allow you to annotate the action in the context of the state it is being linked with.
	For example, the 'caption' property might serve a GUI tooltip or logging statement, and
	the 'validatorMethod' property might specify a target method to invoke on a form action's
	validator.
-->
<!ELEMENT property ( value? )>

<!--
	The name of the property.
-->
<!ATTLIST property name CDATA #REQUIRED>

<!--
	A short-cut alternative to an explicit child 'value' element.
-->
<!ATTLIST property value CDATA #IMPLIED>

<!--
	The value of the property.
-->
<!ELEMENT value ( #PCDATA )>

<!--
	Defines a view state: a state where a view will be rendered.
	Transitions triggered by the view lead on to other states.
-->
<!ELEMENT view-state ( transition+ )>

<!--
	Unique identifier of an view state; must be unique to this flow.
-->
<!ATTLIST view-state id ID #REQUIRED>

<!--
	Optional name of the view that will be rendered when the view state is entered.
	When not present, this view state will be a marker view state.
	A marker view state does not actually render a view, but just returns
	control to the client. Use a marker view state when an action has
	already generated the response.
-->
<!ATTLIST view-state view CDATA #IMPLIED>

<!--
	Defines a transition from one state to another. Transitions define the supported 
	paths through the flow.
-->
<!ELEMENT transition ( property* )>

<!--
	The identifier of the event that can trigger this transition. An event describes something
	that happens e.g "submit", "back", "success", "error".
	Note: in the future, custom transitional expressions will be definable from this element.
-->
<!ATTLIST transition on CDATA #REQUIRED>

<!--
	Target state of the transition.
-->
<!ATTLIST transition to CDATA #REQUIRED>

<!--
	Defines a sub flow state: a state that spawns a sub flow when entered. When the
	sub flow completes execution (reaches a end state), the result of subflow execution
	will be used as grounds for a transition out of this state.
-->
<!ELEMENT subflow-state ( attribute-mapper?, transition+ )>

<!--
	Unique identifier of a subflow state; must be unique to this flow.
-->
<!ATTLIST subflow-state id ID #REQUIRED>

<!--
	Reference to the id of the web flow to be spawned when this subflow state is entered.
-->
<!ATTLIST subflow-state flow CDATA #REQUIRED>

<!--
	An optional mapper that will map attributes from the parent flow to/from the spawned subflow. 
-->
<!ELEMENT attribute-mapper EMPTY>

<!--
	Identifier of the flow attribute mapper implementation exported in the
	configured registry, typically a Spring Bean Factory. This is similar
	to the <ref bean="myBean"/> notation of the Spring beans DTD.
-->
<!ATTLIST attribute-mapper bean CDATA #IMPLIED>

<!--
	Fully qualified class of the flow attribute mapper implementation. An
	instance of the class will be instantiated and possibly autowired
	depending on the value of the autowire attribute.
-->
<!ATTLIST attribute-mapper class CDATA #IMPLIED>
	
<!--
	Dependency (collaborator) autowiring options for use when instantiating the flow attribute mapper
	implementation with the class attribute.
-->
<!ATTLIST attribute-mapper autowire (no | byName | byType | constructor | autodetect | default) "default">

<!--
	Fully qualified implementation class of the flow attribute mapper exported
	in the configured registry. For this "by type" mapper lookup to work, there must
	be exactly one mapper implementation exported of that type.
-->
<!ATTLIST attribute-mapper classref CDATA #IMPLIED>

<!--
	Defines an end state: a state that terminates the flow.
-->
<!ELEMENT end-state EMPTY>

<!--
	Unique identifier of an end state; must be unique to this flow.
-->
<!ATTLIST end-state id ID #REQUIRED>

<!--
	Optional name of the view that will be rendered when this state is reached
	and when there is no parent flow to continue. When not present, this state will be a marker end state.
	A marker end state does not actually render a view, but just returns control to the client.
	Use a marker end state when another object is expected to generate the response.
-->
<!ATTLIST end-state view CDATA #IMPLIED>

=== rubensa/springframework/spring-projects/spring-webflow-samples/sellitem-jsf/src/webapp/WEB-INF/sellItem-flow.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE webflow PUBLIC "-//SPRING//DTD WEBFLOW//EN"
	"http://www.springframework.org/dtd/spring-webflow.dtd">

<webflow id="sellItem" start-state="enterPriceAndItemCount">

	<view-state id="enterPriceAndItemCount" view="/priceAndItemCountForm">
		<transition on="submit" to="anotherEnterPriceAndItemCount">
			<action bean="sellItemAction" />
		</transition>
	</view-state>
	
	<view-state id="anotherEnterPriceAndItemCount" view="/anotherPriceAndItemCountForm">
		<transition on="submit" to="enterCategory">
			<action bean="sellItemAction" />
		</transition>
	</view-state>
	
	<!--  everything from here on still needs to be converted! -->
	
	<view-state id="enterCategory" view="categoryForm">
		<transition on="submit" to="requiresShipping">
			<action bean="sellItemAction" method="bindAndValidate"/>
		</transition>
	</view-state>

	<decision-state id="requiresShipping">
		<if test="${flowScope.sale.shipping}" then="enterShippingDetails" else="showCostOverview"/>
	</decision-state>

	<view-state id="enterShippingDetails" view="shippingDetailsForm">
		<transition on="submit" to="showCostOverview">
			<action bean="sellItemAction" method="bindAndValidate"/>
		</transition>
	</view-state>

	<end-state id="showCostOverview" view="costOverview"/>

</webflow>

=== rubensa/springframework/spring-projects/spring-webflow-samples/birthdate/src/webapp/WEB-INF/birthdate-flow-simplified.xml
<?xml version="1.0" encoding="UTF-8"?>

<!DOCTYPE webflow PUBLIC "-//SPRING//DTD WEBFLOW//EN"
	"http://www.springframework.org/dtd/spring-webflow.dtd">
	
<!-- 
	This simple flow demonstrates the use of the FormAction: a multi-action
	that allows you to mimic the exact behaviour of the SimpleFormController in a flow.
	Notice how all the actions use the same "birthDateFormAction" bean, which groups
	all actions executed by this flow in single class!
	
	Note that this flow implements the exact flow of the SimpleFormController as an example.
	If you only need this flow, it is advised that you just use the SimpleFormController.
	
	This is a simplified definition of the BirthDate flow (see birthDate-flow.xml) that
	uses view state entry actions and transition actions to make the flow definition more compact.
-->
<webflow id="birthdate" start-state="enterBirthdate">

	<view-state id="enterBirthdate" view="enterBirthdate">
		<entry>
			<action bean="formAction" method="setupForm"/>
		</entry>
		<transition on="submit" to="calculateAge">
			<action bean="formAction" method="bindAndValidate"/>
		</transition>
	</view-state>
	
	<action-state id="calculateAge">
		<action name="calculateAge" bean="formAction"/>
		<transition on="calculateAge.success" to="displayAge"/>
	</action-state>
	
	<end-state id="displayAge" view="yourAge"/>

</webflow>

=== rubensa/springframework/spring/samples/webflow/phonebook/src/org/springframework/samples/phonebook/web/flow/search-flow.xml
<?xml version="1.0" encoding="UTF-8"?>

<!DOCTYPE webflow PUBLIC "-//SPRING//DTD WEBFLOW//EN"
	"http://www.springframework.org/dtd/spring-webflow.dtd">

<webflow id="person.Search" start-state="criteria.view">

	<view-state id="criteria.view" view="person.Search.criteria.view">
		<transition on="submit" to="executeQuery">
			<action bean="person.Search.formAction" method="bindAndValidate"/>
		</transition>
	</view-state>

	<action-state id="executeQuery">
		<action bean="person.Search.executeQuery"/>
		<transition on="success" to="results.view"/>
	</action-state>
	
	<view-state id="results.view" view="person.Search.results.view">
		<transition on="newSearch" to="criteria.view"/>
		<transition on="select" to="personId.set"/>
	</view-state>

	<action-state id="personId.set">
		<action bean="person.Search.id.set"/>
		<transition on="success" to="person.Detail"/>
		<transition on="error" to="error"/>
	</action-state>
	
	<subflow-state id="person.Detail" flow="person.Detail">
		<attribute-mapper bean="id.attributeMapper"/>
		<transition on="finish" to="executeQuery"/>
		<transition on="error" to="error"/>
	</subflow-state>
	
	<end-state id="error" view="error.view"/>
	
</webflow>

=== rubensa/springframework/spring-projects/spring-webflow-samples/numberguess/src/webapp/WEB-INF/higherlower.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE webflow PUBLIC "-//SPRING//DTD WEBFLOW//EN"
	"http://www.springframework.org/dtd/spring-webflow.dtd">

<webflow id="higherlower" start-state="enterGuess">
	
	<view-state id="enterGuess" view="enterGuess">
		<transition on="submit" to="guess"/>
	</view-state>
	
	<action-state id="guess">
		<!-- access the stateful action via a proxy -->
		<action bean="higherlowerGameProxy"/>
		<transition on="invalidInput" to="enterGuess"/>
		<transition on="retry" to="enterGuess"/>
		<transition on="success" to="showAnswer"/>
	</action-state>
	
	<end-state id="showAnswer" view="showAnswer"/>

</webflow>
